#!/bin/sh
if [ -n $PWD ] ; then
	d=$(basename $PWD)
else
	d=$(basename `pwd`)
fi
if [ ! -f conf-version ] ; then
	echo "conf-version: No such file or directory" 1>&2
	exit 1
fi
version=$(cat conf-version)
/bin/rm -rf $HOME/stage/$d-$version
mkdir -p $HOME/stage/$d-$version
cp -rp . $HOME/stage/$d-$version
cd $HOME/stage/$d-$version
if [ $? -ne 0 ] ; then
	exit 1
fi
make svcron.spec
make clean
make distclean
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
/bin/rm -rf autom4te.cache
cd ..
tar \
	--exclude="svcron-$version/.git" \
	--exclude="svcron-$version/RCS" \
	--exclude="svcron-$version/debian" \
	--exclude="svcron-$version/crontabs" \
	-cf - svcron-$version | gzip -c > $rpmbuild/SOURCES/svcron-$version.tar.gz
cd svcron-$version
rpmbuild -bb svcron
if test $# -eq 1
then
	rpmbuild -bb --clean --target $1 svcron.spec
else
	rpmbuild -bb --clean svcron.spec
fi
