#!/bin/sh
if [ -n $PWD ] ; then
	d=$(basename $PWD)
else
	d=$(basename `pwd`)
fi
mkdir -p $HOME/stage/$d
cp -rp . $HOME/stage/$d-1.0
cd $HOME/stage/$d-1.0
make clean
make distclean
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
/bin/rm -rf autom4te.cache
cd ..
tar cf - svcron-1.0 |gzip -c > $rpmbuild/SOURCES/svcron-1.0.tar.gz
cd svcron-1.0
rpmbuild -bb svcron
if test $# -eq 1
then
	rpmbuild -bb --clean --target $1 svcron.spec
else
	rpmbuild -bb --clean svcron.spec
fi
